# coding: utf-8

misale1 = Misale.create(:head => 'ለእግሩ የተጠየፈ', :tail => 'ለመቀመጫው ተረፈ', :illustration => 'http://www.acclaimimages.com/_gallery/_images_n300/0041-0909-2806-1147_illustration_worker_taking_a_slip_and_fall.jpg')
misale2 = Misale.create(:head => 'አልጠግብ ባይ', :tail => 'ሲተፋ ያድራል', :illustration => 'http://image.shutterstock.com/display_pic_with_logo/70895/70895,1160512196,5/stock-photo-cartoon-illustration-of-greedy-mouse-eating-sausage-1977948.jpg')
misale3 = Misale.create(:head => 'የራሷ እያረረ', :tail => 'የጎረቤት ታማስላለች', :illustration => 'http://tigrepelvar2.files.wordpress.com/2008/10/cartoon20081002.jpg')
misale4 = Misale.create(:head => 'ጅብ የማያውቁት አገር ሄዶ ', :tail => 'ቁርበት አንጥፉልኝ ይላል', :illustration => 'http://images.quickblogcast.com/17123-16365/640RescuedMortgageCartoonWasserman2007.jpg')                   
misale5 = Misale.create(:head => 'ያላዋቂ ሳሚ', :tail => 'ንፍጥ ይለቀልቃል', :illustration => 'http://1.bp.blogspot.com/_k0ZCGYyFfCg/Seynn9SrRvI/AAAAAAAAAY8/GyteRTIjtNk/s400/palin+cartoon+lipstick.jpg')                                         
misale6 = Misale.create(:head => 'ሰው ጥራ ቢሉት', :tail => 'እራሱ መጣ', :illustration => 'http://4.bp.blogspot.com/_uysYaf3Oi-I/TJn-b9xdb8I/AAAAAAAAB4w/GpK1_Vw5irI/s320/Pointing_Finger.jpg')                                                    
misale7 = Misale.create(:head => 'የአናጺ ቤት', :tail => 'በሩ ሰባራ ነው', :illustration => 'http://t0.gstatic.com/images?q=tbn:ANd9GcTi6eZEUOpGqKM7hElTcMNXDKtIvXKKOeQCyxVlMeUa0o_wLLj2Bw')                                                        
misale8 = Misale.create(:head => 'የፉክክር ቤት', :tail => 'ሳይዘጋ ያድራል', :illustration => 'http://t2.gstatic.com/images?q=tbn:ANd9GcSqLii0BXgEDiB4YEEljbA59KbeuwnzM6kbfc92K7FnzQAJjpEa')                                                         
misale9 = Misale.create(:head => 'ካለመናገር', :tail => 'ደጅአዝማችነት ይቀራል', :illustration => '')                                                                                                                               
misale10 = Misale.create(:head => 'የቆጡን አወርድ ብላ ', :tail => 'የብብትዋን ጣለች', :illustration => '')                                                                                                                           
misale11 = Misale.create(:head => 'የቸኮለ', :tail => 'አፍሶ ለቀመ', :illustration => '')                                                                                                                                                        
misale12 = Misale.create(:head => 'የእነቶሎ ቶሎ ቤት', :tail => 'ግድግዳው ሰንበሌጥ', :illustration => 'http://3.bp.blogspot.com/_g4ZwEWt2sEs/TM67kqwhH-I/AAAAAAAAD3E/AlvwJJKsX0M/s320/HouseOnRock&Sand-Small.jpg')                  
misale13 = Misale.create(:head => 'እጸድቅ ብዬ ባዝላት', :tail => 'ተንጠልጥላ ቀረች', :illustration => 'http://www.hahastop.com/pictures/Pain_In_The_Butt.jpg')                                                                        
misale14 = Misale.create(:head => 'የት አውቅሽ ብሎ', :tail => 'አጥብቆ ሳመኝ', :illustration => 'http://www.flash-screen.com/free-wallpaper/uploads/201010/imgs/1288069154_1440x900_first-kiss.jpg')                                            
misale15 = Misale.create(:head => 'የማይመስል ነገር', :tail => 'ለሚስትህ አትንገር', :illustration => 'http://www.freewebs.com/thebullsheet/NoBull%5B1%5D.jpg')                                                                                   
misale16 = Misale.create(:head => 'ንጉሥ ከሾመው', :tail => 'ማረሻ የሾመው', :illustration => '')                                                                                                                                                        
misale17 = Misale.create(:head => 'ጅብ ከሄደ ', :tail => 'ውሻ ጮኸ', :illustration => '')                                                                                                                                                                      
misale18 = Misale.create(:head => 'ተልባ ቢንጫጫ', :tail => 'ባንድ ሙቀጫ', :illustration => '')                                                                                                                                                           
misale19 = Misale.create(:head => 'ላለፈ ክረምት', :tail => 'ቤት አይሰራም', :illustration => '')                                                                                                                                                        
misale20 = Misale.create(:head => 'ጽድቅና ኩነኔ ቢኖርም ባይኖርም', :tail => 'ከክፋት ደግነት ሳይሻል አይቅርም', :illustration => 'http://www.videoclipart.com/GOOD_EVIL2.jpg')                                                 
misale21 = Misale.create(:head => 'የፈሰሰ ውሃ አይታፈስም', :tail => 'ላለፈ ክረምት ቤት አይሰራም', :illustration => 'http://www.corbisimages.com/images/67/9B576AF5-7A9F-4BEB-85F4-61969841C05E/42-18733979.jpg') 
misale22 = Misale.create(:head => 'ትለብሰው የላት', :tail => 'ትከናነበው አማራት', :illustration => '')                                                                                                                                            
misale23 = Misale.create(:head => 'የምበላው ሳጣ', :tail => 'ልጄ ጥርስ አወጣ', :illustration => '')                                                                                                                                                    
misale24 = Misale.create(:head => 'አይጥ ሞትዋን ስትሻ ስታበዛ ሩጫ', :tail => 'ሄዳ ታሸታለች የድመት አፍንጫ', :illustration => 'http://thescroogereport.files.wordpress.com/2007/12/1_61_mouse_fearless_2.jpg')                   
misale25 = Misale.create(:head => 'ከስቼ ቢያየኝ', :tail => 'ጅማት ለመነኝ', :illustration => 'http://www.matthewsimkins.co.uk/skinny_jeans.JPG')                                                                                                        
misale26 = Misale.create(:head => 'ምንም ብቀጥን ', :tail => 'ጠጅ ነኝ', :illustration => 'http://www.toptenz.net/wp-content/uploads/2009/10/tej.jpg')                                                                                                       
misale27 = Misale.create(:head => 'ሁሉ አማረሽን', :tail => 'ገበያ አታውጧት', :illustration => '')                                                                                                                                                     
misale28 = Misale.create(:head => 'የአህያ ሥጋ', :tail => 'አልጋ ሲሉት መሬት', :illustration => '')                                                                                                                                                    
misale29 = Misale.create(:head => 'ሥጋ ቁጠር ቢሉት', :tail => 'ጣፊያ አንድ አለ', :illustration => '')                                                                                                                                                
misale30 = Misale.create(:head => 'አህያውን ጥሎ', :tail => 'ዳውላውን', :illustration => '')                                                                                                                                                               
misale31 = Misale.create(:head => 'ሲሮጡ የታጠቁት', :tail => 'ሲሮጡ ይፈታል', :illustration => 'http://www.best-of-web.com/_images_300/Cartoon_Man_Tripping_Over_a_Rug_100403-042050-582042.jpg')                                                      
misale32 = Misale.create(:head => 'ፈረስ ያደርሳል እንጂ ', :tail => 'አይዋጋም', :illustration => '')                                                                                                                                                 
misale33 = Misale.create(:head => 'የፈሲታ', :tail => 'ተቆጢታ', :illustration => '')                                                                                                                                                                            
misale34 = Misale.create(:head => 'በልጅ አመካኝቶ', :tail => 'ይበሏል አንኩቶ', :illustration => '')
misale35 = Misale.create(:head => 'ያብዬን እከክ', :tail => 'ወደ እምዬ ልክክ', :illustration => '')
misale36 = Misale.create(:head => 'አይነጋ መስልዋት ', :tail => 'በቋት አራች', :illustration => '')
misale37 = Misale.create(:head => 'ዶሮን ሲያታልሏት', :tail => 'በመጫኛ ጣሏት', :illustration => '')
misale38 = Misale.create(:head => 'ዉሃ ቢወቅጡት', :tail => 'እምቦጭ', :illustration => '')


contact1 = Contact.create(:nickname => 'Alex', :email => 'alemyis@gmail.com', :phone => 12341234)
contact2 = Contact.create(:nickname => 'Zoro', :email => 'zoro@gmail.com', :phone => 12341234)
contact3 = Contact.create(:nickname => 'Ekele', :email => 'ekele@gmail.com', :phone => 12341234)

challenge1 = Challenge.create(:title => 'ሳምንት 1', :note => 'የሳምንት 1 ጥያቄዎች')
challenge2 = Challenge.create(:title => 'ሳምንት 2', :note => 'የሳምንት 2 ጥያቄዎች', :status => 1)

categorization1 = Categorization.create(:misale_id => misale1.id, :challenge_id => challenge1.id,:position => 1)
categorization2 = Categorization.create(:misale_id => misale2.id, :challenge_id => challenge1.id,:position => 2)
categorization3 = Categorization.create(:misale_id => misale3.id, :challenge_id => challenge1.id,:position => 3)
categorization4 = Categorization.create(:misale_id => misale4.id, :challenge_id => challenge1.id,:position => 4)
categorization5 = Categorization.create(:misale_id => misale5.id, :challenge_id => challenge1.id,:position => 5)

categorization6 = Categorization.create(:misale_id => misale6.id, :challenge_id => challenge2.id,:position => 1)
categorization7 = Categorization.create(:misale_id => misale7.id, :challenge_id => challenge2.id,:position => 2)
categorization8 = Categorization.create(:misale_id => misale8.id, :challenge_id => challenge2.id,:position => 3)
categorization9 = Categorization.create(:misale_id => misale9.id, :challenge_id => challenge2.id,:position => 4)
categorization10 = Categorization.create(:misale_id => misale10.id, :challenge_id => challenge2.id,:position => 5)

answer1 = Answer.create(:contact_id => contact1.id, :categorization_id => categorization1.id, :response => 'ተረት ተረት ፣ የላም በረት ፣ አንድ ወፍ ነበረች ፣ እሺ ፣ እሽ ሲሏት በረረች ።', :illustration => '')
answer2 = Answer.create(:contact_id => contact1.id, :categorization_id => categorization2.id, :response => 'ተረት ተረት ፣ የላም በረት ፣ አንድ ወፍ ነበረች ፣ እሺ ፣ እሽ ሲሏት በረረች ።', :illustration => '')
answer3 = Answer.create(:contact_id => contact1.id, :categorization_id => categorization3.id, :response => 'ተረት ተረት ፣ የላም በረት ፣ አንድ ወፍ ነበረች ፣ እሺ ፣ እሽ ሲሏት በረረች ።', :illustration => '')
answer4 = Answer.create(:contact_id => contact1.id, :categorization_id => categorization4.id, :response => 'ተረት ተረት ፣ የላም በረት ፣ አንድ ወፍ ነበረች ፣ እሺ ፣ እሽ ሲሏት በረረች ።', :illustration => '')
answer5 = Answer.create(:contact_id => contact1.id, :categorization_id => categorization5.id, :response => 'ተረት ተረት ፣ የላም በረት ፣ አንድ ወፍ ነበረች ፣ እሺ ፣ እሽ ሲሏት በረረች ።', :illustration => '')

answer01 = Answer.create(:contact_id => contact2.id, :categorization_id => categorization1.id, :response => 'ተረት ተረት ፣ የላም በረት ፣ አንድ ወፍ ነበረች ፣ እሺ ፣ እሽ ሲሏት በረረች ። cat1-cont2', :illustration => '')
answer02 = Answer.create(:contact_id => contact2.id, :categorization_id => categorization2.id, :response => 'ተረት ተረት ፣ የላም በረት ፣ አንድ ወፍ ነበረች ፣ እሺ ፣ እሽ ሲሏት በረረች ። cat2-cont2', :illustration => '')
answer03 = Answer.create(:contact_id => contact2.id, :categorization_id => categorization3.id, :response => 'ተረት ተረት ፣ የላም በረት ፣ አንድ ወፍ ነበረች ፣ እሺ ፣ እሽ ሲሏት በረረች ። cat3-cont2', :illustration => '')
answer04 = Answer.create(:contact_id => contact2.id, :categorization_id => categorization4.id, :response => 'ተረት ተረት ፣ የላም በረት ፣ አንድ ወፍ ነበረች ፣ እሺ ፣ እሽ ሲሏት በረረች ። cat4-cont2', :illustration => '')
answer05 = Answer.create(:contact_id => contact2.id, :categorization_id => categorization5.id, :response => 'ተረት ተረት ፣ የላም በረት ፣ አንድ ወፍ ነበረች ፣ እሺ ፣ እሽ ሲሏት በረረች ። cat5-cont2', :illustration => '')

answer11 = Answer.create(:contact_id => contact3.id, :categorization_id => categorization6.id, :response => 'ተረት ተረት ፣ የላም በረት ፣ አንድ ወፍ ነበረች ፣ እሺ ፣ እሽ ሲሏት በረረች ። cat6-cont3', :illustration => '')
answer12 = Answer.create(:contact_id => contact3.id, :categorization_id => categorization7.id, :response => 'ተረት ተረት ፣ የላም በረት ፣ አንድ ወፍ ነበረች ፣ እሺ ፣ እሽ ሲሏት በረረች ። cat7-cont3', :illustration => '')
answer13 = Answer.create(:contact_id => contact3.id, :categorization_id => categorization8.id, :response => 'ተረት ተረት ፣ የላም በረት ፣ አንድ ወፍ ነበረች ፣ እሺ ፣ እሽ ሲሏት በረረች ። cat8-cont3', :illustration => '')
answer14 = Answer.create(:contact_id => contact3.id, :categorization_id => categorization9.id, :response => 'ተረት ተረት ፣ የላም በረት ፣ አንድ ወፍ ነበረች ፣ እሺ ፣ እሽ ሲሏት በረረች ። cat9-cont3', :illustration => '')
answer15 = Answer.create(:contact_id => contact3.id, :categorization_id => categorization10.id, :response => 'ተረት ተረት ፣ የላም በረት ፣ አንድ ወፍ ነበረች ፣ እሺ ፣ እሽ ሲሏት በረረች ። cat10-cont3', :illustration => '')

comment1_1 = Comment.create(:contact_id => contact1.id, :comment =>'አበበ በሶ በላ ፣ ጫላ ጩቤ ጨበተ ፣  አበበ በሶ በላ ፣ ጫላ ጩቤ ጨበተ ፣  አበበ በሶ በላ ፣ ጫላ ጩቤ ጨበተ ፣  ', :misale_id => misale1.id)
comment1_2 = Comment.create(:contact_id => contact2.id, :comment =>'ተረት ተረት ፣ የላም በረት ፣ አንድ ወፍ ነበረች ፣ እሺ ፣ እሽ ሲሏት በረረች ። ተረት ተረት ፣ የላም በረት ፣ አንድ ወፍ ነበረች ፣ እሺ ፣ እሽ ሲሏት በረረች ። ተረት ተረት ፣ የላም በረት ፣ አንድ ወፍ ነበረች ፣ እሺ ፣ እሽ ሲሏት በረረች ።', :misale_id => misale1.id)
comment1_3 = Comment.create(:contact_id => contact3.id, :comment =>'orem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tortor erat, aliquam sed dignissim non, vestibulum sit amet eros. Duis a nisl lacus. Nunc condimentum nulla nec libero varius posuere imperdiet mi auctor. Aenean convallis sem id augue dictum ornare. Etiam elementum facilisis purus ut tincidunt.', :misale_id => misale1.id)

comment2_1 = Comment.create(:contact_id => contact1.id, :comment =>'አበበ በሶ በላ ፣ ጫላ ጩቤ ጨበተ ፣   አበበ በሶ በላ ፣ ጫላ ጩቤ ጨበተ ፣  ', :misale_id => misale2.id)
comment2_2 = Comment.create(:contact_id => contact2.id, :comment =>'orem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tortor erat, aliquam sed dignissim non, vestibulum sit amet eros. Duis a nisl lacus. Nunc condimentum nulla nec libero varius posuere imperdiet mi auctor. Aenean convallis sem id augue dictum ornare. Etiam elementum facilisis purus ut tincidunt.', :misale_id => misale2.id)

comment3_1 = Comment.create(:contact_id => contact3.id, :comment =>'አበበ በሶ በላ ፣ ጫላ ጩቤ ጨበተ ፣  አበበ በሶ በላ ፣ ጫላ ጩቤ ጨበተ ፣  አበበ በሶ በላ ፣ ጫላ ጩቤ ጨበተ ፣  አበበ በሶ በላ ፣ ጫላ ጩቤ ጨበተ ፣  ', :misale_id => misale3.id)

